### ISSUE TITLE
Passwörter gegen haveibeenpwned prüfen

### ISSUE THREAD

**Issue by stesie** [WueWW/wueww-tool#13]
es gibt eine API, über die wir auf bereits als unsicher bekannte Passwörter prüfen lassen können.

Evtl. mögen wir die verwenden?

**Comment by CasiCrispi** [comment]
Gerne. Ich kann dazu leider keinen Input liefern, weil ich mich damit gar nicht auskenne.

**Comment by stesie** [comment]
ja machen, is lustig :)
