### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by stesie** [WueWW/wueww-tool#14]
Wir brauchen bestimmt ein Impressum; und sowas wie zwei, drei Zeilen zur Verarbeitung der Daten.

Wer wird da als Ansprechpartner:in genannt?

**Comment by CasiCrispi** [comment]
Bitte meinen Namen angeben. Impressum haben wir auch auf der Webseite: https://wueww.de/impressum/

Ich warte noch auf eine überarbeitete Datenschutzerklärung von Holger Loos. Werde da mal Montag nachfragen, die können wir dann hier verwenden.

**Comment by CasiCrispi** [comment]
Kurzes Update zur Datenschutzerklärung: Noch kein Feedback von Holger erhalten. Melde mich, wenn ich dazu was habe.

**Comment by CasiCrispi** [comment]
Ich habe die Nutzungsbedingungen enthalten. 

[Nutzungsbedingungen Veranstalter-Portal.docx](https://github.com/WueWW/wueww-tool/files/3901735/Nutzungsbedingungen.Veranstalter-Portal.docx)
