### ISSUE TITLE
Mainpost Beilage Export

### ISSUE THREAD

**Issue by stesie** [WueWW/wueww-tool#22]
einfaches Textfile

Gegliedert nach Datum; darunter je Session eine Zeile; Beispiel folgt

**Comment by CasiCrispi** [comment]
Hier sind die Daten vom letzten Jahr


[Kalendarium WueWW 2019.pdf](https://github.com/WueWW/wueww-tool/files/4097547/Kalendarium.WueWW.2019.pdf)

Falls du das Word-Dokument brauchst ...
