### ISSUE TITLE
Bestätigungslink "Anmeldung für WueWW-Tool"

### ISSUE THREAD

**Issue by CasiCrispi** [WueWW/wueww-tool#26]
Hej,

schön, dass du dich für das WueWW Tool registriert hast.  

Bestätige bitte noch deine E-Mail-Adresse (und damit dein Benutzerkonto), indem auf folgenden Link klickst:
http://wueww-tool.metafnord.de/user/registration/b8927890d9367982446e334eb234972bbd42fc99

Viele Grüße

das WueWW-Team

**Comment by stesie** [comment]
nach "indem" soll vermutlich noch ein "du"?

**Comment by CasiCrispi** [comment]
Ja, sorry.
