### ISSUE TITLE
Text auf Startseite

### ISSUE THREAD

**Issue by CasiCrispi** [WueWW/wueww-tool#27]
Willkommen bei Utes Helferlein. Als Veranstalter/Veranstalterin kannst du hier Termine für die Wuerzburg Web Week einstellen.

Nachdem du ein Benutzerkonto erstellt hast, vervollständige bitte die Veranstalterangaben. Danach kannst du gleich den ersten Termin anlegen. Keine Sorge, das geht dauert nicht lange. 

Wie geht es danach weiter? 

Die von dir erfassten Daten werden schnellstmöglich von uns freigeschaltet und auf der Webseite im Programm hinzugefügt. Selbstverständlich kannst du die Angaben jederzeit ändern. Wenn du noch Fragen hast, meld dich bitte bei kontakt@wueww.de.

Bei Neu hier?

Dann ist der nächste Schritt, dass du dir ein Benutzerkonto anlegst und die E-Mail-Adresse anschließend bestätigst.

Du warst schon mal hier? <-- (Leerzeichen zwischen schon und mal)

_Rest passt_

**Comment by stesie** [comment]
das erste "geht" habe ich weggelassen, das gehört da meines Erachtens nicht hin

**Comment by stesie** [comment]
Hmm, hier steht noch "Termin", soll das mit Blick auf #29 dann nicht auch Event heißen?

**Comment by CasiCrispi** [comment]
Ja, das muss dann auch Event heißen

**Comment by CasiCrispi** [comment]
Außerdem ist mir noch ein kleiner Fehler aufgefallen: 

"Die von dir erfassten Daten werden schnellstmöglich von uns freigeschaltet ..." --> es muss freigeschalten heißen, Plural.
