### ISSUE TITLE
Workflow "Session freigeben"

### ISSUE THREAD

**Issue by CasiCrispi** [WueWW/wueww-tool#28]
Aktuell kann ich vom Workflow her, eine E-Mail an den Veranstalter schicken, oder ich kann die Session freigeben; dann verschwindet aber der Hinweis auf die E-Mail. 

Mir wäre es lieb, wenn ich erst die Session freigebe und dann die E-Mail schicke. Heißt, der Link mit "E-Mail an Veranstalter senden" bleibt dann noch erhalten. Geht das?

<img width="1139" alt="WueWW-Tool-Sessionfreigeben" src="https://user-images.githubusercontent.com/57127856/69013847-0a84d800-0985-11ea-8535-ffdd3a447524.png">

**Comment by stesie** [comment]
Hab' oberhalb der Box mal noch einen Abschnitt mit Veranstalterangaben eingefügt (den nur der Editor sieht); da ist nun auch die E-Mail Adresse drin (und nur dort), aber immer sichtbar
