### ISSUE TITLE
Eigenes Feld für Gebäudenamen?

### ISSUE THREAD

**Issue by CasiCrispi** [WueWW/wueww-tool#33]
Ist es sinnvoll für Gebäudenamen ein eigenes Feld zwischen Locationname und Straße anzulegen. Oder bei Locationname auch erwähnen, dass man dort Geäbudenamen angibt. Was meinst du? 

<img width="821" alt="Screenshot Veranstaltungsort" src="https://user-images.githubusercontent.com/57127856/69360611-2a6d1200-0c8b-11ea-97f9-60c6a7251171.png">

<img width="1159" alt="Screenshot Veranstaltungsort_formular" src="https://user-images.githubusercontent.com/57127856/69360731-5be5dd80-0c8b-11ea-98f9-eb02307e92d6.png">

**Comment by stesie** [comment]
würde sagen bei "ggf. Firmenname" mit aufführen reicht völlig; ist ja doch eher edge-case
