### ISSUE TITLE
500er: Veranstaltung mit bereits verwendeter E-Mail Adresse

### ISSUE THREAD

**Issue by EdwardBock** [WueWW/wueww-tool#42]
Hi @stesie 

wir haben gerade festgestellt, dass beim Anlegen einer Veranstaltung mit einer E-Mail Adresse die bereits einer anderen Veranstaltung zugewiesen ist, der Vorgang mit einem 500er abgebrochen wird und der folgende Fehler im Apache error.log steht.

```log
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ute.muendlein@wueww.de' for key 'UNIQ_8D93D649E7927C74'" at /var/sites/wueww-tool/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55
2020-01-22T15:18:46+01:00 [critical] Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (email, roles, password, registration_complete) VALUES (?, ?, ?, ?)' with params ["ute.muendlein@wueww.de", "[]", "!", 1]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ute.muendlein@wueww.de' for key 'UNIQ_8D93D649E7927C74'" at /var/sites/wueww-tool/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 55
```

**Comment by stesie** [comment]
mmh, ich würde wetten, dass ihr keine neue Veranstaltung anlegt, sondern als Admin auf Veranstalter und dann "Neuen Veranstalter anlegen", ... da entsteht hintenrum nämlich ein User ohne Passwort ;-)

... und dafür muss die E-Mail Adresse natürlich unique sein.

Nichts desto trotz sollte er natürlich eine Fehlermeldung bringen :)
