### ISSUE TITLE
Alle freigegebenen Veranstaltung in session.json 

### ISSUE THREAD

**Issue by kroppenstedt** [WueWW/wueww-tool#45]
Moin @stesie, 

in der session.json ist bei uns aktuell nur eine Veranstaltung - es sind jedoch 4 freigegeben. Gibt es für den Export noch ein Script was angestoßen werden muss oder ein Cacheing?

**Comment by stesie** [comment]
ihr müsst die zugehörigen Veranstalter auch noch freigeben ;-)

**Comment by kroppenstedt** [comment]
Okay, dann ist es etwas verwirrend, dass unter dem Event im Backend steht, dass dies freigegeben ist.
